# Linear Algebra
In this tutorial we will be looking at basic linear algebra operations.
in the realm of ML and DL we think of everything as vectors!
if you want to take the input of a house with the following feratures:

1 m^2

2 # of rooms

3 balcony or not

An example of one house would be denoted as the following: <120,3,0>
and this hoouse would be 120m^2 with 3 rooms and no balconies!
tutorial from D2l.ai: https://d2l.ai/chapter_preliminaries/linear-algebra.html

In [11]:
import torch
# a vector with 5 elements
x = torch.arange(5)
x.shape

torch.Size([5])

In [10]:
print(x[1:4])
len(x)

tensor([1, 2, 3])


5

In [12]:
# you can think of matrices as multiple vectors i.e multiple houses!
A = torch.arange(15).reshape(3,-1)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [14]:
A.shape

torch.Size([3, 5])

In [22]:
#tensors: In mathematics, a tensor is an algebraic object that describes a (multilinear) 
#relationship between sets of algebraic objects related to a vector space. Objects that 
#tensors may map between include vectors and scalars, and even other tensors.(wikipedia)

#for example with RNNs: more on this later:
# your input will be (input_size,time_stamps,# of features)!

X = torch.arange(32).reshape(2,4,4)
X

# we have two examples with 4 time stamps and each input i.e time stamp has 4 features!


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]])

# Tensor Arithmetic

### Hadamard product of matrices  A and  B

\begin{split}\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.\end{split}

In [34]:
#add samples:
print(f'Adding samples: \n {X.sum(axis = 0)}')
#add time stamps:
print(f'Adding time stamps: \n {X.sum(axis = 1)}')


Adding samples: 
 tensor([[16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]])
Adding time stamps: 
 tensor([[ 24,  28,  32,  36],
        [ 88,  92,  96, 100]])


In [36]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [38]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.shape, x.shape, torch.mv(A, x)


(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [42]:
u = torch.tensor([-3.0, 4.0,5])
torch.norm(u)

tensor(7.0711)

In [50]:
torch.sqrt(torch.abs(u).pow(2).sum())

tensor(7.0711)

In [56]:
((torch.abs(u).pow(4).sum())).pow(1/4)

tensor(5.5692)

# Automatic differentiation

Derivatives play a crucial role in almost all Deep learning optimization algorithms!
Intuitively, derivatives show us how much the loss function changes when parameters are changed i.e rate of change.


In [63]:
x = torch.arange(3.0 , requires_grad = True)
y = 3*torch.dot(x,x) #should be equal to 15.
y

tensor(15., grad_fn=<MulBackward0>)

In [64]:
y.backward()
#3*x^2 ==> 6x  
x.grad

tensor([ 0.,  6., 12.])

In [65]:
x.grad == 6 * x

tensor([True, True, True])

In [71]:
# pytorch accumulates the gradient by default, we need to clear the previous values!

x.grad.zero_()
y = x.sum()
print(y)


tensor(3., grad_fn=<SumBackward0>)


In [72]:
y.backward()
#sum(x) ==> 1. 
x.grad

tensor([1., 1., 1.])

In [77]:
x.grad.zero_()
y = x*x
print(y)
y.sum().backward()
x.grad

tensor([0., 1., 4.], grad_fn=<MulBackward0>)


tensor([0., 2., 4.])

In [79]:
x.grad.zero_()
y = torch.dot(x,x) #should be 5.
print(y)
y.backward()
x.grad #should be 2*x

tensor(5., grad_fn=<DotBackward>)


tensor([0., 2., 4.])

In [80]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
print(x.grad)
u

tensor([0., 1., 4.])


tensor([0., 1., 4.])

In [82]:
x.grad.zero_()
y = x * x
#here z = x^3
u = y
z = u * x

z.sum().backward()
print(x.grad)
u

tensor([ 0.,  3., 12.])


tensor([0., 1., 4.], grad_fn=<MulBackward0>)