In mathematics, a tensor is an algebraic object that describes a (multilinear) relationship between sets of algebraic objects related to a vector space. Objects that tensors may map between include vectors and scalars, and even other tensors(wikipedia).
In deep learning the concept of tensors are of crucial importance since they are what store data. Learning about data manipulation will help you understand the backbones of deep learning

In [7]:
import torch
x = torch.arange(10)
print(x.dtype)
x

torch.int64


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = x.reshape(-1,2)

In [15]:
x.shape

torch.Size([5, 2])

In [16]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [20]:
torch.zeros((5,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [21]:
torch.ones(2,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [30]:
#random number generator:
x = 0
while(x<10):
    print(torch.rand(3,4))
    x+=1
    if(x == 9):
        break
    print("------------------")

tensor([[0.1560, 0.1960, 0.0237, 0.2574],
        [0.9483, 0.7895, 0.6717, 0.1459],
        [0.7333, 0.9065, 0.6768, 0.4436]])
------------------
tensor([[0.7211, 0.0083, 0.3949, 0.4931],
        [0.8143, 0.2546, 0.3775, 0.7905],
        [0.8630, 0.3330, 0.4819, 0.5811]])
------------------
tensor([[0.6870, 0.1164, 0.5724, 0.1861],
        [0.4065, 0.2900, 0.4513, 0.3218],
        [0.1521, 0.5475, 0.4057, 0.4278]])
------------------
tensor([[0.6727, 0.8932, 0.0575, 0.4166],
        [0.4836, 0.2635, 0.7960, 0.1622],
        [0.6797, 0.8138, 0.1322, 0.1133]])
------------------
tensor([[0.2574, 0.2309, 0.0040, 0.5608],
        [0.3478, 0.5888, 0.0447, 0.5223],
        [0.4541, 0.2480, 0.2513, 0.1732]])
------------------
tensor([[0.1016, 0.4585, 0.4654, 0.0592],
        [0.0184, 0.2184, 0.3766, 0.2989],
        [0.5868, 0.6982, 0.1346, 0.7032]])
------------------
tensor([[0.2272, 0.1211, 0.7152, 0.9912],
        [0.7714, 0.5193, 0.7985, 0.1776],
        [0.8324, 0.2110, 0.4323, 0.7728]

In [42]:
x = torch.tensor([2.,3,2])
y = torch.tensor([1,2,2])
print(x.dtype)
x*y

torch.float32


tensor([2., 6., 4.])

In [40]:
#exponentials are always used for non-linearities:
torch.exp(x)

tensor([ 7.3891, 20.0855,  7.3891])

In [50]:
#find mean of data!
x = torch.arange(15.)
print(x.dtype)
print(x.sum()/len(x))
x.mean()

torch.float32
tensor(7.)


tensor(7.)

In [53]:
#find the standard deviation!
x.std()

tensor(4.4721)

In [60]:
a = torch.arange(10).reshape(-1,5)
b = torch.ones(10).reshape(-1,5)
#dim  = 0 -> add as rows 
#dim = 1 -> add as columns
torch.cat((a,b) , dim = 1)

tensor([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
        [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

In [63]:
a == b

tensor([[False,  True, False, False, False],
        [False, False, False, False, False]])

In [70]:
A = torch.tensor([[2,5,3],[20,50,60],[80,90,55],[2,1,2]])
A[1:,2]

tensor([60, 55,  2])

In [78]:
B = torch.arange(20).reshape(-1,5,4)
B.shape

torch.Size([1, 5, 4])

In [83]:
B

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]])

In [85]:
B[0,1:,1]

tensor([ 5,  9, 13, 17])

In [91]:
#manipulate variables using the same memory location. Also known as in-place operations

Z = torch.zeros_like(A)
print(f'id: {id(Z)}')
Z = Z+A
print(f'id: {id(Z)}')

id: 140387786684480
id: 140387786697344


In [93]:
Z = torch.zeros_like(A)
a = id(Z)
print(f'id: {id(Z)}')
Z[:] = Z+A
b = id(Z)
print(f'id: {id(Z)}')
a == b

id: 140387786704448
id: 140387786704448


True

End of class 1!